### ISSUE TITLE
GRAL fails to build with JDK 1.7

### ISSUE THREAD

**Issue by eseifert** [eseifert/gral#52]
When building with JDK 1.7 there are several errors during unit test in DummyJdbc class:

```
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/user/GRAL/gral-core/src/test/java/de/erichseifert/gral/DummyJdbc.java:[60,7] error: DummyJdbc is not abstract and does not override abstract method getNetworkTimeout() in Connection
[ERROR] /home/user/GRAL/gral-core/src/test/java/de/erichseifert/gral/DummyJdbc.java:[280,0] error: DummyDataBaseMetaData is not abstract and does not override abstract method generatedKeyAlwaysReturned() in DatabaseMetaData
[ERROR] /home/user/GRAL/gral-core/src/test/java/de/erichseifert/gral/DummyJdbc.java:[1015,0] error: DummyResultSet is not abstract and does not override abstract method <T>getObject(String,Class<T>) in ResultSet
[ERROR]
T extends Object declared in method <T>getObject(String,Class<T>)
/home/user/GRAL/gral-core/src/test/java/de/erichseifert/gral/DummyJdbc.java:[1972,0] error: DummyPreparedStatement is not abstract and does not override abstract method isCloseOnCompletion() in Statement
[INFO] 4 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] GRAL build tools .................................. SUCCESS [3.324s]
[INFO] GRAL graphing library ............................. SUCCESS [48.634s]
[INFO] GRAL core ......................................... FAILURE [13.142s]
[INFO] GRAL example applications ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:05.408s
[INFO] Finished at: Wed Nov 30 15:10:23 CET 2011
[INFO] Final Memory: 21M/141M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:testCompile (default-testCompile) on project gral-core: Compilation failure: Compilation failure:
[ERROR] /home/user/GRAL/gral-core/src/test/java/de/erichseifert/gral/DummyJdbc.java:[60,7] error: DummyJdbc is not abstract and does not override abstract method getNetworkTimeout() in Connection
[ERROR] /home/user/GRAL/gral-core/src/test/java/de/erichseifert/gral/DummyJdbc.java:[280,0] error: DummyDataBaseMetaData is not abstract and does not override abstract method generatedKeyAlwaysReturned() in DatabaseMetaData
[ERROR] /home/user/GRAL/gral-core/src/test/java/de/erichseifert/gral/DummyJdbc.java:[1015,0] error: DummyResultSet is not abstract and does not override abstract method <T>getObject(String,Class<T>) in ResultSet
[ERROR]
[ERROR] T extends Object declared in method <T>getObject(String,Class<T>)
[ERROR] /home/user/GRAL/gral-core/src/test/java/de/erichseifert/gral/DummyJdbc.java:[1972,0] error: DummyPreparedStatement is not abstract and does not override abstract method isCloseOnCompletion() in Statement
```

Thanks to Mathieu Leclaire for reporting the issue.

 _Imported from trac ticket #53,  created by eseifert on 12-01-2011 at 15:07, last modified: 12-01-2011 at 20:21_

**Comment by eseifert** [comment]
The problem is caused by changes to the JDBC API with Java 7: although build target is set to Java 1.5 the new API methods are expected during build. 

[r420](None/changeset/420/historical) and [r421](None/changeset/421/historical) add the missing API methods and building works fine with JDK 1.7 now:
```
mvn clean package assembly:assembly
```

However, ProGuard (for making GRALs JAR files smaller) isn't working with JDK 1.7 at the moment, so
```
mvn -Pproguard clean package assembly:assembly
```
will still fail. This should be fixed too as soon as possible.

_Trac comment by eseifert on 12-01-2011 at 15:13_

**Comment by eseifert** [comment]
Marking this bug as fixed because building works now with JDK 1.7. ProGuard has no fix yet but version 4.7 beta supports Java 7 and will hopefully be released soon.

Ticket can be reopened when needed.

_Trac comment by eseifert on 12-01-2011 at 20:21_
